# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    # Use the WPILib docker container
    container: wpilib/roborio-cross-ubuntu:2024-22.04

    steps:
    - uses: actions/checkout@v4
 
    # Declare the repository safe
    - name: Add repository to git safe directories
      run: git config --global --add safe.directory $GITHUB_WORKSPACE

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    
    - name: Execute Gradle build
      run: ./gradlew test

    - name: Send status to Slack
      if: always()
      id: slack
      uses: slackapi/slack-github-action@v1.25.0
      with:
        channel-id: 'C8Q6UHPA5'
        payload: |
          {
            "text": "GitHub Action: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }} #${{ github.run_number }}>\nStatus: ${{ job.status }}\nBranch/Tag: ${{ github.ref_name }}\nTriggered by: ${{ github.actor }}"
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}